'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.18052
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "Funktion zum automatischen Speichern von My.Settings"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("smtp.magnet.ch")>  _
        Public ReadOnly Property MySmtpServer() As String
            Get
                Return CType(Me("MySmtpServer"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("spwebService@sputnik-it.com")>  _
        Public ReadOnly Property errMailFrom() As String
            Get
                Return CType(Me("errMailFrom"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("error@sputnik-it.ch")>  _
        Public ReadOnly Property errMailSubject() As String
            Get
                Return CType(Me("errMailSubject"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Fehler...")>  _
        Public ReadOnly Property errMailBody() As String
            Get
                Return CType(Me("errMailBody"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Password=1234;Persist Security Info=True;User ID=GAVUser;Initial Catalog=Sputnik "& _ 
            "InfoSystem;Data Source=192.168.19.53")>  _
        Public ReadOnly Property Connstr_InfoService() As String
            Get
                Return CType(Me("Connstr_InfoService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Password=1234;Persist Security Info=True;User ID=GAVUser;Initial Catalog=Sputnik "& _ 
            "GAV;Data Source=192.168.19.53")>  _
        Public ReadOnly Property ConnStr_ServiceUtil() As String
            Get
                Return CType(Me("ConnStr_ServiceUtil"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Password=12SPContract_User34;Persist Security Info=True;User ID=SPContract_User;I"& _ 
            "nitial Catalog=spContract;Data Source=192.168.19.53")>  _
        Public ReadOnly Property SettingDb_Connection() As String
            Get
                Return CType(Me("SettingDb_Connection"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Password=12SPContract_User34;Persist Security Info=True;User ID=SPContract_User;I"& _ 
            "nitial Catalog=spContract;Data Source=192.168.19.53")>  _
        Public ReadOnly Property ConnStr_JobCh() As String
            Get
                Return CType(Me("ConnStr_JobCh"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Password=12SPContract_User34;Persist Security Info=True;User ID=SPContract_User;I"& _ 
            "nitial Catalog=Sputnik InfoSystem;Data Source=192.168.19.53")>  _
        Public ReadOnly Property ConnStr_SputnikInfoSystem() As String
            Get
                Return CType(Me("ConnStr_SputnikInfoSystem"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Password=1234;Persist Security Info=True;User ID=GAVUser;Initial Catalog=Sputnik "& _ 
            "GAV;Data Source=192.168.19.53")>  _
        Public ReadOnly Property ConnStr_SputnikGAV() As String
            Get
                Return CType(Me("ConnStr_SputnikGAV"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Password=12SPContract_User34;Persist Security Info=True;User ID=SPContract_User;I"& _ 
            "nitial Catalog=spContract;Data Source=192.168.19.53")>  _
        Public ReadOnly Property ConnStr_Vak() As String
            Get
                Return CType(Me("ConnStr_Vak"),String)
            End Get
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.wsSPS_Services_x86.My.MySettings
            Get
                Return Global.wsSPS_Services_x86.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
