'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.239
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "Funktion zum automatischen Speichern von My.Settings"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Sputnik Cockpit")>  _
        Public ReadOnly Property DBName() As String
            Get
                Return CType(Me("DBName"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Mustermann AG")>  _
        Public ReadOnly Property CustomerName() As String
            Get
                Return CType(Me("CustomerName"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("7E43DA9185BDB24FF2B4E73BD74DBA8406D568A6")>  _
        Public ReadOnly Property ServerCertThumbprint() As String
            Get
                Return CType(Me("ServerCertThumbprint"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.19.52;Initial Catalog=""Sputnik Cockpit"";Integrated Security=T"& _ 
            "rue")>  _
        Public ReadOnly Property SputnikCockpit_ConnectionString() As String
            Get
                Return CType(Me("SputnikCockpit_ConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://localhost:1331/TableDataUploadService.svc")>  _
        Public ReadOnly Property EndpointAddress() As String
            Get
                Return CType(Me("EndpointAddress"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("MIICLTCCAZqgAwIBAgIQBCE2szVhQIBI0OcT/6KAVjAJBgUrDgMCHQUAMCkxJzAlBgNVBAMTHm15Y29ja"& _ 
            "3BpdFdlYlNlcnZpY2VDZXJ0aWZpY2F0ZTAeFw0xMTEwMjEwODM5MDFaFw0zOTEyMzEyMzU5NTlaMCkxJ"& _ 
            "zAlBgNVBAMTHm15Y29ja3BpdFdlYlNlcnZpY2VDZXJ0aWZpY2F0ZTCBnzANBgkqhkiG9w0BAQEFAAOBj"& _ 
            "QAwgYkCgYEA4Zmcj7i7CpY9e1efJK9gVMiUjWY+X29kHc5Tbl2lKIutZVtsW1GmKwJ0CKLk+Y4NpyK+P"& _ 
            "hW3XrIPgMyIKqDj/qHUOxtdx05ocut9pOdHs3tX3vxqsBgQ39GEJ4O+0fJ5Dv18G6fLMh9OIIUkDOlU1"& _ 
            "dfCQGZyGTVKAzmEgLauVCUCAwEAAaNeMFwwWgYDVR0BBFMwUYAQaZQIMSTKLVajwuk2Z4NAhKErMCkxJ"& _ 
            "zAlBgNVBAMTHm15Y29ja3BpdFdlYlNlcnZpY2VDZXJ0aWZpY2F0ZYIQBCE2szVhQIBI0OcT/6KAVjAJB"& _ 
            "gUrDgMCHQUAA4GBAIyrrWYNMB+w+krqjdl7vsqrNdYXpN9SxsCGeG7wi7RHg4v59ol93syexEh24OH+G"& _ 
            "h4fsCok0vF+9KrLbgUjTNCo7G3NzEZHtgLFpwA2Hh5iPIVbnIJlyL/M1aC2K3ewkEHizN7BB4+kitfO+"& _ 
            "R1aeSqDPYrYbLyOjVX2QNOpwt96")>  _
        Public ReadOnly Property Certificate() As String
            Get
                Return CType(Me("Certificate"),String)
            End Get
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.UploadClient.My.MySettings
            Get
                Return Global.UploadClient.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
