'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "Funktion zum automatischen Speichern von My.Settings"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Password=12SPContract_User34;Persist Security Info=True;User ID=SPContract_User;I"& _ 
            "nitial Catalog=spUpdates;Data Source=192.168.19.53")>  _
        Public ReadOnly Property connectionString() As String
            Get
                Return CType(Me("connectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public ReadOnly Property RootconnectionString() As String
            Get
                Return CType(Me("RootconnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\Temp\")>  _
        Public ReadOnly Property FileSaveToLocation() As String
            Get
                Return CType(Me("FileSaveToLocation"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("smtp.magnet.ch")>  _
        Public ReadOnly Property MySmtpServer() As String
            Get
                Return CType(Me("MySmtpServer"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public ReadOnly Property bSaveAllLOGS() As Boolean
            Get
                Return CType(Me("bSaveAllLOGS"),Boolean)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public ReadOnly Property bSaveJustErrors() As Boolean
            Get
                Return CType(Me("bSaveJustErrors"),Boolean)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public ReadOnly Property bDeleteUploadFile() As Boolean
            Get
                Return CType(Me("bDeleteUploadFile"),Boolean)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("spwebService@sputnik-it.com")>  _
        Public ReadOnly Property errMailFrom() As String
            Get
                Return CType(Me("errMailFrom"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("error@sputnik-it.ch")>  _
        Public ReadOnly Property errMailTo() As String
            Get
                Return CType(Me("errMailTo"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Fehler...")>  _
        Public ReadOnly Property errMailSubject() As String
            Get
                Return CType(Me("errMailSubject"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Anbei eine Fehlermeldung...")>  _
        Public ReadOnly Property errMailBody() As String
            Get
                Return CType(Me("errMailBody"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Password=1234;Persist Security Info=True;User ID=GAVUser;Initial Catalog=Sputnik "& _ 
            "GAV;Data Source=192.168.19.115")>  _
        Public ReadOnly Property ConnStr_GAV() As String
            Get
                Return CType(Me("ConnStr_GAV"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Password=12SPContract_User34;Persist Security Info=True;User ID=SPContract_User;I"& _ 
            "nitial Catalog=spContract;Data Source=192.168.19.53")>  _
        Public ReadOnly Property ConnStr_Vak() As String
            Get
                Return CType(Me("ConnStr_Vak"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Password=12SPContract_User34;Persist Security Info=True;User ID=SPContract_User;I"& _ 
            "nitial Catalog=spContract;Data Source=192.168.19.53")>  _
        Public ReadOnly Property ConnStr_MA() As String
            Get
                Return CType(Me("ConnStr_MA"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\Temp\WS_Err.Text")>  _
        Public ReadOnly Property strErrorLOGFile() As String
            Get
                Return CType(Me("strErrorLOGFile"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\Temp\WS_Prog.Text")>  _
        Public ReadOnly Property strProgLOGFile() As String
            Get
                Return CType(Me("strProgLOGFile"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Password=12SPContract_User34;Persist Security Info=True;User ID=SPContract_User;I"& _ 
            "nitial Catalog=spContract;Data Source=192.168.19.53")>  _
        Public ReadOnly Property ConnStr_KD() As String
            Get
                Return CType(Me("ConnStr_KD"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Password=12SPContract_User34;Persist Security Info=True;User ID=SPContract_User;I"& _ 
            "nitial Catalog=spSystemInfo;Data Source=192.168.19.70")>  _
        Public ReadOnly Property ConnStr_SystemInfo() As String
            Get
                Return CType(Me("ConnStr_SystemInfo"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Password=12SPContract_User34;Persist Security Info=True;User ID=SPContract_User;I"& _ 
            "nitial Catalog=spContract;Data Source=192.168.19.53")>  _
        Public ReadOnly Property SettingDb_Connection() As String
            Get
                Return CType(Me("SettingDb_Connection"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Password=12SPContract_User34;Persist Security Info=True;User ID=SPContract_User;I"& _ 
            "nitial Catalog=spScanJobs;Data Source=192.168.19.70")>  _
        Public ReadOnly Property ConnStr_Scanning() As String
            Get
                Return CType(Me("ConnStr_Scanning"),String)
            End Get
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.SPWebService.My.MySettings
            Get
                Return Global.SPWebService.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
